#Ensure your repository Secrets for DOCKER_USERNAME, DOCKER_PASSWORD,are properly configured
#This pipeline is configured for spring boot applications
name: CI/CD Pipeline

on:
  push:
    branches: #Add additional branches if we neeed to add additional branches
      - main 
      - dev
      - test
      - <Your_branch_name_here>

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn package
        env:
          API_KEY: ${{ secrets.API_KEY }}

      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image # Edit regions if you would like to deploy to different regions
        run: |
          docker build -t <dockerhub username>/<dockerhub repository>:<name_you_want_your_image_to_be> .

      - name: Push Docker image to Docker Hub
        run: |
          docker push <dockerhub username>/<dockerhub repository>:<name_you_want_your_image_to_be>

